alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

alias ls='ls --group-directories-first --color=auto'
alias lh='ls -lh'
alias ll='ls -l'
alias la='ls -la'
alias l.='ls -a'
alias lr='ls -ltR'
alias log='clear;sudo tail -f /var/log/syslog'
alias lo='exit'
alias backup='mv $1 $1-.`date +'%m-%d-%y.%H:%M:%S'`'
alias h='history'
alias lt='ls -ltr'
alias adback='adb backup -f SM_G530T-`date +'%m-%d-%y.%H:%M:%S'`.ab -apk -obb -all -system'
alias klog='clear;tail -f ${HOME}/.kodi/temp/kodi.log'
